### PR TITLE
File renamer enhancements

### PR DESCRIPTION
**Pull request by jayjun911**
- adding DisplayVersion support
- closing file of parent window on renamer opening (so the file can be renamed without being locked)

### CODE REVIEW

**Comment by jayjun911** [comment]
now with using "XCIUpdateVer" to add updated display version of the patch included, and number of addons 
ex) {Title} [{TitleId:U}][v{VerNum}]+[u{XCIUpdateVer}].{Ext:L}

will rename XCI files contains patch and multiple addons as...

"Game Title [0100xxxxxxxxxxx][v0]**+[u1.0.7+12DLC]**.xci"

**Comment by Myster-Tee** [comment]
Hey mate, sorry for late response, I'm very busy...
Why did you close you PR?

**Comment by jayjun911** [comment]
I saw v3.0 and wanted to resolve any conflicts and re-PR

**Comment by jayjun911** [comment]
I've submitted a new PR for v3. , no conflict.

**Pull request closed without merging**
